# For more information see https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#triggers
trigger:
- master
- main

stages:
- stage: Build

  variables:
    buildConfiguration: Release
    solutionName: AzurePipelinesExample
  
  jobs:
  - job: Build

    # Workspace only has to be specified for self-hosted agents.
    # For more information,see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#workspace
    workspace:
      clean: outputs
    
    steps:
    - template: '.azure-pipelines/build-and-verify-dotnet-solution.yml'
      inputs:
        solutionName: ''
      
    